GET http://localhost:3000/tweets

###
GET  http://localhost:3000/tweets/2

###
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "text": "Teste 4"
}

###
PATCH http://localhost:3000/tweets/3
Content-Type: application/json

{
    "text": "Teste 3 update 3"
}

###
DELETE http://localhost:3000/tweets/4